#version: "3.9"
services:
  pgdatabase:  #this is the host name for the server
    image: postgres:13
    environment:
      - POSTGRES_USER="root"
      - POSTGRES_PASSWORD="root"
      - POSTGRES_DB="ny_taxi"
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=ROOT
    ports:
      - "8080:80"


# DOCKER COMPOSE ALLOWS FOR ME TO NOT NEET TO CREATE A NETWORK WHEN RUNNING DOCKER. IT HAPPENS AUTOMATICALLY
# docker-compose up   or with -d for detached
# ctrl-c to quit the run
# docker-compose down to properly quit it